// frontend/src/layouts/MainLayout.tsx
import { useState } from 'react'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { Layout, Menu } from '@arco-design/web-react'
import {
  IconHome,
  IconSync,
  IconLeft,
  IconRight,
} from '@arco-design/web-react/icon'

const { Sider, Content } = Layout

const menuItems = [
  { key: '/', label: '首页', icon: <IconHome /> },
  { key: '/sync', label: '同步记录', icon: <IconSync /> },
]

export default function MainLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const [collapsed, setCollapsed] = useState(false)

  return (
    <Layout style={{ height: '100vh' }}>
      <Sider
        collapsible
        collapsed={collapsed}
        onCollapse={(val: boolean) => setCollapsed(val)}
        trigger={collapsed ? <IconRight /> : <IconLeft />}
        width={200}
        collapsedWidth={64}
        style={{ borderRight: '1px solid var(--color-border)' }}
      >
        <div
          style={{
            padding: 16,
            fontSize: 20,
            fontWeight: 'bold',
            textAlign: 'center',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
          }}
        >
          {collapsed ? 'P' : 'PAI'}
        </div>
        <Menu
          selectedKeys={[location.pathname]}
          onClickMenuItem={(key: string) => navigate(key)}
          collapse={collapsed}
        >
          {menuItems.map((item) => (
            <Menu.Item key={item.key}>
              {item.icon}
              {item.label}
            </Menu.Item>
          ))}
        </Menu>
      </Sider>
      <Layout>
        <Content style={{ padding: 24 }}>
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  )
}

// frontend/src/layouts/MainLayout.vue
<script setup lang="ts">
import { h, ref } from 'vue'
import { useRouter } from 'vue-router'
import { NLayout, NLayoutSider, NLayoutContent, NMenu, NIcon } from 'naive-ui'
import type { MenuOption } from 'naive-ui'
import { HomeOutline, SyncOutline } from '@vicons/ionicons5'

const router = useRouter()
const collapsed = ref(false)

function renderIcon(icon: any) {
  return () => h(NIcon, null, { default: () => h(icon) })
}

const menuOptions: MenuOption[] = [
  {
    label: '首页',
    key: 'home',
    icon: renderIcon(HomeOutline),
  },
  {
    label: '同步记录',
    key: 'sync',
    icon: renderIcon(SyncOutline),
  },
]

function handleMenuClick(key: string) {
  router.push({ name: key })
}
</script>

<template>
  <n-layout has-sider style="height: 100vh">
    <n-layout-sider
      bordered
      :collapsed="collapsed"
      collapse-mode="width"
      :collapsed-width="64"
      :width="200"
      show-trigger
      @collapse="collapsed = true"
      @expand="collapsed = false"
    >
      <div
        style="
          padding: 16px;
          font-size: 20px;
          font-weight: bold;
          text-align: center;
          white-space: nowrap;
          overflow: hidden;
        "
      >
        {{ collapsed ? 'P' : 'PAI' }}
      </div>
      <n-menu
        :collapsed="collapsed"
        :collapsed-width="64"
        :collapsed-icon-size="22"
        :options="menuOptions"
        :value="String($route.name)"
        @update:value="handleMenuClick"
      />
    </n-layout-sider>
    <n-layout>
      <n-layout-content content-style="padding: 24px;">
        <router-view />
      </n-layout-content>
    </n-layout>
  </n-layout>
</template>
